# 开发环境配置文件
server:
  port: 8800
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rabbit?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: RB-Token
    # token有效期，单位s 默认30天
    timeout: 3600
    # 在多人登录同一账号时，是否共享会话 (为true时共用一个，为false时新登录挤掉旧登录)
    is-share: true
    # 是否尝试从请求体里读取token
    is-read-body: false
    # 是否尝试从header里读取token
    is-read-head: true
    # 是否尝试从cookie里读取token
    is-read-cookie: false
    # 是否在初始化配置时打印版本字符画
    is-v: false


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapping/*Mapper.xml

# 是否开启 swagger
swagger:
  enable: true
